package ge.tbca.city_park.core.domain.util

enum class ApiError:ResourceError {
    UNAUTHORIZED,
    UNKNOWN_ERROR,
    INTERNAL_SERVER_ERROR,
    INVALID_REQUEST,
    MISSING_USER_ID,
    PARKING_SPOT_NOT_FOUND,
    NO_AVAILABLE_SPOTS,
    INVALID_ID_FORMAT,
    RESERVATION_NOT_FOUND,
    CAR_ALREADY_RESERVED,
    USER_ALREADY_HAS_RESERVATION,
    USER_NOT_FOUND,
    CARD_NOT_FOUND,
    CAR_NOT_FOUND,
    CAR_ALREADY_EXISTS,
    CARD_ALREADY_EXISTS,
    CARD_EXPIRED,
    INSUFFICIENT_BALANCE

    

}